import re

# Read current file
with open('src/services/masterDataService.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Define the new INITIAL_PANEL_CATALOG
new_catalog = '''// ============================================================================
// VERIFIED CENTRALIZED ALUMINUM FORMWORK MASTER CATALOG SEEDS
// ============================================================================
export const INITIAL_PANEL_CATALOG: PanelMasterCatalogItem[] = [
  // 1. Internal Wall Panels
  {
    id: "CAT-IWP-1200-600",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Internal Wall",
    panelType: "Internal Wall Panel",
    panelName: "Internal Wall Standard Modular Panel",
    panelCode: "IWP-1200-600",
    standardDimension: "1200 × 600 × 65 mm",
    length: 1200,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 14.8,
    description: "Standard modular 1.2m internal room partition panel with tie-rod sleeves and pin holes at 50mm centers.",
    manufacturerRef: "MIV-IWP-1260",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "SP-200"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-IWP-2400-600",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Internal Wall",
    panelType: "Internal Wall Panel",
    panelName: "Internal Wall Full-Height Panel",
    panelCode: "IWP-2400-600",
    standardDimension: "2400 × 600 × 65 mm",
    length: 2400,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 28.5,
    description: "2.4m full-height vertical internal shear wall panel engineered with 4.0mm alloy 6061-T6 face skin.",
    manufacturerRef: "MIV-IWP-2460",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-IWP-2700-600",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Internal Wall",
    panelType: "Internal Wall Panel",
    panelName: "Internal Wall Extended High-Clearance Panel",
    panelCode: "IWP-2700-600",
    standardDimension: "2700 × 600 × 65 mm",
    length: 2700,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 32.1,
    description: "2.7m extended internal shear wall panel for residential high-ceiling living areas.",
    manufacturerRef: "KK-IWP-2760",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "PPP-2538"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-IWP-2400-450",
    manufacturer: "Aluma Systems International",
    formworkSystem: "Aluma EasySet 65mm",
    panelCategory: "Internal Wall",
    panelType: "Internal Wall Panel",
    panelName: "Internal Wall Corridor & Jamb Panel",
    panelCode: "IWP-2400-450",
    standardDimension: "2400 × 450 × 65 mm",
    length: 2400,
    width: 450,
    thickness: 65,
    unit: "mm",
    weightKg: 21.6,
    description: "Medium-width partition panel for corridors and doorway returns.",
    manufacturerRef: "ALU-IWP-2445",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-IWP-3000-600",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "Internal Wall",
    panelType: "Internal Wall Panel",
    panelName: "Internal Wall Podium & Lobby Panel",
    panelCode: "IWP-3000-600",
    standardDimension: "3000 × 600 × 65 mm",
    length: 3000,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 35.8,
    description: "3.0-meter high-clearance wall panel for lobby architectural interior walls.",
    manufacturerRef: "GETO-IWP-3060",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "PPP-2538"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 2. External Wall Panels
  {
    id: "CAT-EWP-1200-900",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "External Wall",
    panelType: "External Wall Panel",
    panelName: "External Wall Wide Modular Panel",
    panelCode: "EWP-1200-900",
    standardDimension: "1200 × 900 × 65 mm",
    length: 1200,
    width: 900,
    thickness: 65,
    unit: "mm",
    weightKg: 22.4,
    description: "Wide-format exterior facade panel equipped with perimeter weather-seal groove.",
    manufacturerRef: "MIV-EWP-1290",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "WB-300"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-EWP-2400-600",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "External Wall",
    panelType: "External Wall Panel",
    panelName: "External Facade Heavy-Duty Panel",
    panelCode: "EWP-2400-600",
    standardDimension: "2400 × 600 × 70 mm",
    length: 2400,
    width: 600,
    thickness: 70,
    unit: "mm",
    weightKg: 31.0,
    description: "Heavy-duty exterior wall panel with 70mm frame profile and reinforced ribs for high wind pressures.",
    manufacturerRef: "GETO-EWP-2460",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "KP-150-2400"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-EWP-2700-600",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "External Wall",
    panelType: "External Wall Panel",
    panelName: "External Facade High-Clearance Panel",
    panelCode: "EWP-2700-600",
    standardDimension: "2700 × 600 × 65 mm",
    length: 2700,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 33.2,
    description: "Full-height exterior facade shutter with integrated tie holes and kicker landing flange.",
    manufacturerRef: "KK-EWP-2760",
    compatibleAccessories: ["TR-15", "WN-15", "PC-22", "WP-PIN-01", "WEDGE-01", "PPP-2538"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 3. Extend Panels
  {
    id: "CAT-EXT-600-600",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Extend Panel",
    panelType: "Extend Panel",
    panelName: "Extend Panel Square Modular",
    panelCode: "EXT-600-600",
    standardDimension: "600 × 600 × 65 mm",
    length: 600,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 7.8,
    description: "Vertical height extension panel mounted above standard 2.4m wall panels for ceiling level adjustments.",
    manufacturerRef: "MIV-EXT-6060",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "CL-65"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-EXT-300-600",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Extend Panel",
    panelType: "Extend Panel",
    panelName: "Extend Panel 300mm Infill",
    panelCode: "EXT-300-600",
    standardDimension: "300 × 600 × 65 mm",
    length: 600,
    width: 300,
    thickness: 65,
    unit: "mm",
    weightKg: 4.5,
    description: "Precision 300mm vertical height extension shutter.",
    manufacturerRef: "KK-EXT-3060",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "CL-65"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 4. Soffit Panels
  {
    id: "CAT-SOF-1200-600",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Soffit Panel",
    panelType: "Soffit Panel",
    panelName: "Soffit Modular Transition Panel",
    panelCode: "SOF-1200-600",
    standardDimension: "1200 × 600 × 65 mm",
    length: 1200,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 14.2,
    description: "Soffit corner and edge panel supporting early wall stripping while maintaining continuous slab propping.",
    manufacturerRef: "MIV-SOF-1260",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525", "SP-200"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-SOF-150-2400",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Soffit Panel",
    panelType: "Soffit Panel",
    panelName: "Soffit Length Corner Strip",
    panelCode: "SO-150-2400",
    standardDimension: "150 × 2400 × 65 mm",
    length: 2400,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 11.5,
    description: "Wall-to-slab transition soffit angle extrusion for quick-strip drop-head systems.",
    manufacturerRef: "KK-SO-1524",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 5. Beam Panels
  {
    id: "CAT-BM-1500-300",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Beam Panel",
    panelType: "Beam Panel",
    panelName: "Structural Beam Bottom & Side Panel",
    panelCode: "BM-1500-300",
    standardDimension: "1500 × 300 × 65 mm",
    length: 1500,
    width: 300,
    thickness: 65,
    unit: "mm",
    weightKg: 11.8,
    description: "Reinforced modular beam bottom and side panel with prop-head brackets.",
    manufacturerRef: "MIV-BM-1530",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-BM-1200-400",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Beam Panel",
    panelType: "Beam Panel",
    panelName: "Deep Girder Beam Side Panel",
    panelCode: "BM-1200-400",
    standardDimension: "1200 × 400 × 65 mm",
    length: 1200,
    width: 400,
    thickness: 65,
    unit: "mm",
    weightKg: 12.6,
    description: "Modular beam formwork for 400mm drop-depth transfer beams.",
    manufacturerRef: "KK-BM-1240",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 6. CA Panels (Chamfer Angle / Corner Angle)
  {
    id: "CAT-CA-100-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "CA Panel",
    panelType: "CA Panel",
    panelName: "Chamfer Angle Bevel Corner Panel",
    panelCode: "CA-100-2400",
    standardDimension: "100 × 100 × 2400 mm",
    length: 2400,
    width: 100,
    thickness: 65,
    unit: "mm",
    weightKg: 12.5,
    description: "45-degree architectural chamfer corner extrusion preventing chipping at column and wall corners.",
    manufacturerRef: "MIV-CA-1024",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-CA-75-2400",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "CA Panel",
    panelType: "CA Panel",
    panelName: "Chamfer Angle 75mm Bevel Panel",
    panelCode: "CA-75-2400",
    standardDimension: "75 × 75 × 2400 mm",
    length: 2400,
    width: 75,
    thickness: 65,
    unit: "mm",
    weightKg: 9.8,
    description: "75mm chamfer angle transition extrusion for monolithic edge finishing.",
    manufacturerRef: "GETO-CA-7524",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 7. IC Panels (Internal Corner)
  {
    id: "CAT-IC-150-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "IC Panel",
    panelType: "IC Panel",
    panelName: "Internal Corner 90° Angle Panel",
    panelCode: "IC-150-2400",
    standardDimension: "150 × 150 × 2400 mm",
    length: 2400,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 18.6,
    description: "Rigid 90-degree internal angle connection panel linking perpendicular room shear walls.",
    manufacturerRef: "MIV-IC-1524",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-IC-200-2400",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "IC Panel",
    panelType: "IC Panel",
    panelName: "Internal Corner 200mm Core Panel",
    panelCode: "IC-200-2400",
    standardDimension: "200 × 200 × 2400 mm",
    length: 2400,
    width: 200,
    thickness: 65,
    unit: "mm",
    weightKg: 23.4,
    description: "Heavy internal corner panel for elevator shafts and stair core 90° junctions.",
    manufacturerRef: "GETO-IC-2024",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 8. SC Panels (Soffit Corner)
  {
    id: "CAT-SC-150-1200",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "SC Panel",
    panelType: "SC Panel",
    panelName: "Soffit Corner Beam Junction Panel",
    panelCode: "SC-150-1200",
    standardDimension: "150 × 150 × 1200 mm",
    length: 1200,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 10.2,
    description: "Soffit corner angle forming horizontal wall-to-deck or beam-to-slab transition corners.",
    manufacturerRef: "KK-SC-1512",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 9. SCR Panels (Soffit Corner Return)
  {
    id: "CAT-SCR-150-150",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "SCR Panel",
    panelType: "SCR Panel",
    panelName: "Soffit Corner Return 3-Way Junction",
    panelCode: "SCR-150-150",
    standardDimension: "150 × 150 × 150 mm",
    length: 150,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 2.8,
    description: "Precision 3-dimensional corner component connecting wall corner, beam corner, and slab soffit.",
    manufacturerRef: "MIV-SCR-1515",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 10. Slab Panels
  {
    id: "CAT-SP-1200-1200",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Slab Panel",
    panelType: "Slab Panel",
    panelName: "Slab Decking Square Modular Panel",
    panelCode: "SP-1200-1200",
    standardDimension: "1200 × 1200 × 65 mm",
    length: 1200,
    width: 1200,
    thickness: 65,
    unit: "mm",
    weightKg: 24.2,
    description: "Standard square horizontal slab deck panel with reinforced underside cross-ribs for deflection control.",
    manufacturerRef: "KK-SP-1212",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-SP-900-1800",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Slab Panel",
    panelType: "Slab Panel",
    panelName: "Large-Span Slab Decking Panel",
    panelCode: "SP-900-1800",
    standardDimension: "900 × 1800 × 65 mm",
    length: 1800,
    width: 900,
    thickness: 65,
    unit: "mm",
    weightKg: 31.4,
    description: "Large-span horizontal slab deck panel for high-efficiency floor decking.",
    manufacturerRef: "KK-SP-1890",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-2538"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-SP-600-1200",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Slab Panel",
    panelType: "Slab Panel",
    panelName: "Modular Slab Infill Panel",
    panelCode: "SP-600-1200",
    standardDimension: "600 × 1200 × 65 mm",
    length: 1200,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 14.8,
    description: "Modular slab panel for infill zones, perimeter spans, and early prop-head strip intervals.",
    manufacturerRef: "MIV-SP-1260",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 11. Door End Panels
  {
    id: "CAT-DEP-2100-200",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Door End Panel",
    panelType: "Door End Panel",
    panelName: "Door Opening Jamb End Panel",
    panelCode: "DEP-2100-200",
    standardDimension: "2100 × 200 × 65 mm",
    length: 2100,
    width: 200,
    thickness: 65,
    unit: "mm",
    weightKg: 16.5,
    description: "Full-height vertical closure panel for standard 2.1m doorway openings in shear wall layouts.",
    manufacturerRef: "MIV-DEP-2120",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-DEP-2100-150",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Door End Panel",
    panelType: "Door End Panel",
    panelName: "Door Opening 150mm End Panel",
    panelCode: "DEP-2100-150",
    standardDimension: "2100 × 150 × 65 mm",
    length: 2100,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 13.2,
    description: "150mm wall thickness doorway jamb termination formwork.",
    manufacturerRef: "KK-DEP-2115",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 12. Wall End Panels
  {
    id: "CAT-WEP-2400-200",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Wall End Panel",
    panelType: "Wall End Panel",
    panelName: "Wall Termination End Bulkhead Panel",
    panelCode: "WEP-2400-200",
    standardDimension: "2400 × 200 × 65 mm",
    length: 2400,
    width: 200,
    thickness: 65,
    unit: "mm",
    weightKg: 17.8,
    description: "Vertical stop-end panel closing off free wall ends and window opening sides.",
    manufacturerRef: "MIV-WEP-2420",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-WEP-2700-200",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Wall End Panel",
    panelType: "Wall End Panel",
    panelName: "Wall End Extended Bulkhead Panel",
    panelCode: "WEP-2700-200",
    standardDimension: "2700 × 200 × 65 mm",
    length: 2700,
    width: 200,
    thickness: 65,
    unit: "mm",
    weightKg: 19.8,
    description: "2.7m extended wall end closure panel for high-clearance shear wall terminations.",
    manufacturerRef: "KK-WEP-2720",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 13. Corner Panels
  {
    id: "CAT-CP-300-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Corner Panel",
    panelType: "Corner Panel",
    panelName: "Corner Compensation Alignment Panel",
    panelCode: "CP-300-2400",
    standardDimension: "300 × 2400 × 65 mm",
    length: 2400,
    width: 300,
    thickness: 65,
    unit: "mm",
    weightKg: 16.5,
    description: "Corner adjustment panel installed adjoining internal corners for precise grid dimensioning.",
    manufacturerRef: "MIV-CP-2430",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 14. Internal Corners
  {
    id: "CAT-IC-STD-150-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Internal Corner",
    panelType: "Internal Corner",
    panelName: "Standard Internal 90° Corner",
    panelCode: "IC-150-2400-STD",
    standardDimension: "150 × 150 × 2400 mm",
    length: 2400,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 18.6,
    description: "Internal corner extrusion connecting right-angled interior shear walls.",
    manufacturerRef: "MIV-IC-90-24",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 15. External Corners
  {
    id: "CAT-EC-65-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "External Corner",
    panelType: "External Corner",
    panelName: "Standard External 90° Clamp Profile",
    panelCode: "EC-65-2400",
    standardDimension: "65 × 65 × 2400 mm",
    length: 2400,
    width: 65,
    thickness: 65,
    unit: "mm",
    weightKg: 9.8,
    description: "Rigid 90-degree outer corner extrusion clamping external wall panels together.",
    manufacturerRef: "MIV-EC-6524",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "CL-65"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 16. Column Panels
  {
    id: "CAT-COL-600-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Column Panel",
    panelType: "Column Panel",
    panelName: "Structural Column Shutter Panel",
    panelCode: "COL-600-2400",
    standardDimension: "600 × 2400 × 65 mm",
    length: 2400,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 28.5,
    description: "Heavy-duty column shuttering panel engineered for high hydrostatic concrete head pressure.",
    manufacturerRef: "MIV-COL-2460",
    compatibleAccessories: ["TR-15", "WN-15", "CL-80", "WB-300", "WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-COL-750-2400",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "Column Panel",
    panelType: "Column Panel",
    panelName: "Wide Column Perimeter Shutter",
    panelCode: "COL-750-2400",
    standardDimension: "750 × 2400 × 65 mm",
    length: 2400,
    width: 750,
    thickness: 65,
    unit: "mm",
    weightKg: 34.2,
    description: "Wide column panel for structural core columns in commercial buildings.",
    manufacturerRef: "GETO-COL-2475",
    compatibleAccessories: ["TR-15", "WN-15", "CL-80", "WB-300", "WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 17. Stair Panels (Dedicated Category & Parameters - Prompt 10)
  {
    id: "CAT-STP-FLT-1200",
    manufacturer: "Geto Aluminum Formwork Co.",
    formworkSystem: "Geto High-Rise 65mm",
    panelCategory: "Stair Panel",
    panelType: "Stair Panel",
    panelName: "Monolithic Stair Flight Panel (10 Steps)",
    panelCode: "STP-FLT-1200",
    standardDimension: "1200 × 300 × 65 mm",
    length: 3000,
    width: 1200,
    thickness: 65,
    unit: "mm",
    weightKg: 42.5,
    description: "Complete monolithic flight shutter for 10-step staircases with 300mm tread and 150mm riser.",
    manufacturerRef: "GETO-STP-1200",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15", "PPP-1525"],
    stairConfig: {
      stairPanelType: "Flight Panel",
      stairWidth: 1200,
      tread: 300,
      riser: 150,
      slopeAngle: 30.5,
      numberOfSteps: 10
    },
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-STP-FLT-1000",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Stair Panel",
    panelType: "Stair Panel",
    panelName: "Standard Stair Flight Panel (8 Steps)",
    panelCode: "STP-FLT-1000",
    standardDimension: "1000 × 280 × 65 mm",
    length: 2400,
    width: 1000,
    thickness: 65,
    unit: "mm",
    weightKg: 36.0,
    description: "8-step residential stair flight formwork with 280mm tread and 175mm riser at 32° slope.",
    manufacturerRef: "KK-STP-1000",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15", "PPP-1525"],
    stairConfig: {
      stairPanelType: "Flight Panel",
      stairWidth: 1000,
      tread: 280,
      riser: 175,
      slopeAngle: 32.0,
      numberOfSteps: 8
    },
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-STP-LND-1200",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Stair Panel",
    panelType: "Stair Panel",
    panelName: "Stair Intermediate Landing Panel",
    panelCode: "STP-LND-1200",
    standardDimension: "1200 × 1200 × 65 mm",
    length: 1200,
    width: 1200,
    thickness: 65,
    unit: "mm",
    weightKg: 24.5,
    description: "Intermediate rest landing horizontal shuttering panel for stair core enclosures.",
    manufacturerRef: "MIV-STP-LND",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    stairConfig: {
      stairPanelType: "Landing Panel",
      stairWidth: 1200,
      tread: 300,
      riser: 150,
      slopeAngle: 0,
      numberOfSteps: 1
    },
    isVerifiedStandard: true,
    isActive: true
  },

  // 18. Beam Soffit Panels
  {
    id: "CAT-BS-1200-300",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Beam Soffit",
    panelType: "Beam Soffit",
    panelName: "Beam Underside Soffit Panel",
    panelCode: "BS-1200-300",
    standardDimension: "1200 × 300 × 65 mm",
    length: 1200,
    width: 300,
    thickness: 65,
    unit: "mm",
    weightKg: 9.6,
    description: "Horizontal underside soffit shutter supporting concrete beams between vertical supports.",
    manufacturerRef: "MIV-BS-1230",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "PPP-1525"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 19. Beam Side Panels
  {
    id: "CAT-BSI-1200-500",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Beam Side",
    panelType: "Beam Side",
    panelName: "Deep Beam Side Wall Panel",
    panelCode: "BSI-1200-500",
    standardDimension: "1200 × 500 × 65 mm",
    length: 1200,
    width: 500,
    thickness: 65,
    unit: "mm",
    weightKg: 15.2,
    description: "Vertical beam side shutter designed for 500mm deep concrete perimeter beams.",
    manufacturerRef: "MIV-BSI-1250",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 20. Filler Panels
  {
    id: "CAT-FP-100-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Filler Panel",
    panelType: "Filler Panel",
    panelName: "100mm Precision Tolerance Filler",
    panelCode: "FP-100-2400",
    standardDimension: "100 × 2400 × 65 mm",
    length: 2400,
    width: 100,
    thickness: 65,
    unit: "mm",
    weightKg: 6.8,
    description: "Dimensional adjustment panel for custom room spans and structural tolerances.",
    manufacturerRef: "MIV-FP-1024",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },
  {
    id: "CAT-FP-50-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Filler Panel",
    panelType: "Filler Panel",
    panelName: "50mm Gap Infill Extrusion",
    panelCode: "FP-50-2400",
    standardDimension: "50 × 2400 × 65 mm",
    length: 2400,
    width: 50,
    thickness: 65,
    unit: "mm",
    weightKg: 4.2,
    description: "50mm precision gap filler extrusion for non-standard room layouts.",
    manufacturerRef: "MIV-FP-5024",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 21. Kicker Panels
  {
    id: "CAT-KP-150-2400",
    manufacturer: "Kumkang Kind Formwork",
    formworkSystem: "Kumkang 65mm Standard System",
    panelCategory: "Kicker Panel",
    panelType: "Kicker Panel",
    panelName: "Starter Slab Footing Kicker",
    panelCode: "KP-150-2400",
    standardDimension: "150 × 2400 × 65 mm",
    length: 2400,
    width: 150,
    thickness: 65,
    unit: "mm",
    weightKg: 9.6,
    description: "Bottom alignment starter kicker bolted to the concrete slab edge to anchor upper-floor wall panels.",
    manufacturerRef: "KK-KP-1524",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 22. Stop End Panels
  {
    id: "CAT-SEP-2400-200",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan 65mm Standard System",
    panelCategory: "Stop End Panel",
    panelType: "Stop End Panel",
    panelName: "Construction Joint Stop-End Panel",
    panelCode: "SEP-2400-200",
    standardDimension: "2400 × 200 × 65 mm",
    length: 2400,
    width: 200,
    thickness: 65,
    unit: "mm",
    weightKg: 18.2,
    description: "Bulkhead stop-end shutter equipped with rebar comb slots for construction cold joints.",
    manufacturerRef: "MIV-SEP-2420",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 23. Platform / Working Panels
  {
    id: "CAT-PWP-1200-800",
    manufacturer: "Aluma Systems International",
    formworkSystem: "Aluma EasySet 65mm",
    panelCategory: "Platform/Accessory Panel",
    panelType: "Platform/Working Panel",
    panelName: "External Scaffold Working Platform",
    panelCode: "PWP-1200-800",
    standardDimension: "1200 × 800 × 65 mm",
    length: 1200,
    width: 800,
    thickness: 65,
    unit: "mm",
    weightKg: 19.5,
    description: "Perforated non-slip worker access deck panel mounted on external wall climbing brackets.",
    manufacturerRef: "ALU-PWP-1280",
    compatibleAccessories: ["WB-800", "WP-PIN-01", "WEDGE-01"],
    isVerifiedStandard: true,
    isActive: true
  },

  // 24. Special Panels
  {
    id: "CAT-LS-600-2400",
    manufacturer: "Mivan Technology Corp",
    formworkSystem: "Mivan Monolithic High-Rise",
    panelCategory: "Special Panel",
    panelType: "Special Panel",
    panelName: "Quick-Stripping Core Shaft Panel",
    panelCode: "LS-600-2400",
    standardDimension: "600 × 2400 × 65 mm",
    length: 2400,
    width: 600,
    thickness: 65,
    unit: "mm",
    weightKg: 29.5,
    description: "Elevator shaft inner formwork panel configured with crane-lift stripping corners.",
    manufacturerRef: "MIV-LS-2460",
    compatibleAccessories: ["WP-PIN-01", "WEDGE-01", "TR-15", "WN-15", "PPP-2538"],
    isVerifiedStandard: true,
    isActive: true
  }
];
'''

# Find pattern from // Verified Global down to export const INITIAL_MASTER_PROJECTS
start_idx = content.find('// Verified Global / International Aluminum Formwork Panel Master Catalog Seeds')
end_idx = content.find('export const INITIAL_MASTER_PROJECTS: MasterProjectRecord[] = [')

if start_idx != -1 and end_idx != -1:
    content = content[:start_idx] + new_catalog + '\n\n' + content[end_idx:]
    with open('src/services/masterDataService.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print("INITIAL_PANEL_CATALOG updated successfully")
else:
    print(f"Error: start={start_idx}, end={end_idx}")
