import React, { useState } from "react";
import { 
  initialWorkers, 
  initialTeams, 
  initialZones, 
  initialAttendance, 
  initialEvaluations, 
  initialProgressLogs, 
  initialSafetyLogs, 
  initialQualitySnags, 
  initialQualityLogs,
  initialAuditLogs
} from "./data";
import { 
  Worker, 
  Team, 
  ProjectZone, 
  AttendanceRecord, 
  PerformanceEvaluation, 
  DailyProgressLog, 
  SafetyLog, 
  QualitySnag, 
  QualityLog, 
  UserRole,
  AuditLog
} from "./types";

// Component imports
import { Dashboard } from "./components/Dashboard";
import { Attendance } from "./components/Attendance";
import { PlanningScheduler } from "./components/PlanningScheduler";
import { DailyProgress } from "./components/DailyProgress";
import { Performance } from "./components/Performance";
import { SafetyQuality } from "./components/SafetyQuality";
import { AIPredictions } from "./components/AIPredictions";
import { AdminPanel } from "./components/AdminPanel";
import { AuditLogView } from "./components/AuditLogView";
import { AiPhotoInspection } from "./components/AiPhotoInspection";
import { BiometricAttendanceBoard } from "./components/BiometricAttendanceBoard";
import { FingerprintAttendanceBoard } from "./components/FingerprintAttendanceBoard";
import { BiometricEnrollmentKiosk } from "./components/BiometricEnrollmentKiosk";

// Lucide Icons
import { 
  Building2, 
  Users, 
  Calendar, 
  Layers, 
  ShieldAlert, 
  Activity, 
  Sparkles, 
  Settings, 
  VolumeX,
  Languages,
  UserCheck,
  ShieldCheck,
  Camera,
  Fingerprint,
  ScanLine
} from "lucide-react";

export default function App() {
  // Master State Arrays
  const [workers, setWorkers] = useState<Worker[]>(initialWorkers);
  const [teams, setTeams] = useState<Team[]>(initialTeams);
  const [zones, setZones] = useState<ProjectZone[]>(initialZones);
  const [attendance, setAttendance] = useState<AttendanceRecord[]>(initialAttendance);
  const [evaluations, setEvaluations] = useState<PerformanceEvaluation[]>(initialEvaluations);
  const [progressLogs, setProgressLogs] = useState<DailyProgressLog[]>(initialProgressLogs);
  const [safetyLogs, setSafetyLogs] = useState<SafetyLog[]>(initialSafetyLogs);
  const [qualitySnags, setQualitySnags] = useState<QualitySnag[]>(initialQualitySnags);
  const [qualityLogs, setQualityLogs] = useState<QualityLog[]>(initialQualityLogs);

  // Shell UI parameters
  const [currentUserRole, setCurrentUserRole] = useState<UserRole>(UserRole.HEAD_OFFICE);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>(initialAuditLogs);
  const [isAmharic, setIsAmharic] = useState(true);
  const [activeTab, setActiveTab] = useState("dashboard");

  // Multi-Language Translation Map
  const translations: Record<string, Record<string, string>> = {
    en: {
      "Dashboard": "Dashboard",
      "Attendance": "Attendance",
      "Biometric Board": "Biometric Board",
      "Fingerprint Board": "Fingerprint Board",
      "Biometric Kiosk": "Biometric Kiosk & Enroll",
      "Planning": "Planning & Scheduler",
      "Daily Logs": "Daily Logs",
      "Evaluation": "Performance Evaluation",
      "Safety & Quality": "Safety & Quality",
      "AI Predictions": "AI Forecasting Core",
      "Admin": "Admin Console",
      "Workers Present": "Workers Present",
      "Late": "Late",
      "Absent": "Absent",
      "Leave": "Leave",
      "Active Zones": "Active Zones",
      "Delayed Zones": "Delayed Zones",
      "Safety Score": "Safety Compliance Index",
      "Quality Score": "Quality Audit Index",
      "Top Performing Workers": "Top Rated Workers",
      "Top Performing Teams": "Top Rated Teams",
      "Simulate Attendance Tap": "Register Biometric Check-In/Out",
      "Select Worker": "Select Site Worker",
      "Select Attendance Method": "Attendance Scan Method",
      "Clock In (IN)": "Clock In",
      "Clock Out (OUT)": "Clock Out",
      "Worker Attendance Logs": "Worker Attendance Register",
      "Worker Name": "Worker Name",
      "Trade": "Trade Specialty",
      "Check In": "Check-In Time",
      "Check Out": "Check-Out Time",
      "Working Hours": "Logged Hours",
      "Method": "Scan Tool",
      "Status": "Status",
      "Project Planner & Scheduler": "OVID Aluminum Cycle Scheduler",
      "Project Start Date": "Cycle Commencement Date",
      "Number of Floors": "Estimated Floors",
      "Zones per Floor": "Working Zones/Floor",
      "Target Days per Zone": "Target Duration/Zone",
      "Generate Construction Schedule": "Generate Master Construction Schedule",
      "Zone Schedule Table": "Autogenerated Structural Gantt Timeline",
      "Record Daily Formwork Progress": "Track Daily Panel Assemblies",
      "Building & Block": "Building Bloc & Target",
      "Floor & Zone": "Floor",
      "Installed Panels": "Lock Panels Installed",
      "Removed Panels": "Panels Stripped/Prepped",
      "Remaining Panels": "Panels Stacked",
      "Concrete Ready for Pouring": "Pre-pour Check Passed",
      "Inspection Status": "Quality Audit Sign-off",
      "Comments": "Daily Site Log Notes",
      "Log Daily Progress": "Submit Progress Entry",
      "Add Quality Snag": "Log Alignment Defect / Snag",
      "Defect Type": "Defect Category",
      "Active Snags & Repair Status": "Outstanding Defects Registry",
    },
    am: {
      "Dashboard": "ዋና ሰሌዳ (Dashboard)",
      "Attendance": "የመገኘት ቁጥጥር (Attendance)",
      "Biometric Board": "ባዮሜትሪክ ሰሌዳ",
      "Fingerprint Board": "የጣት አሻራ ሰሌዳ",
      "Biometric Kiosk": "ባዮሜትሪክ ኪዮስክ እና ምዝገባ",
      "Planning": "ማቀጃ እና የጊዜ ሰሌዳ (Scheduler)",
      "Daily Logs": "የእለት ስራዎች ምዝገባ (Daily Logs)",
      "Evaluation": "የሰራተኞች ግምገማ (Performance)",
      "Safety & Quality": "ደህንነት እና ጥራት (Safety/Quality)",
      "AI Predictions": "አይአይ ትንበያ (AI Predictions)",
      "Admin": "አስተዳደር ፓነል (Admin)",
      "Workers Present": "የመጡ ሰራተኞች",
      "Late": "የዘገዩ",
      "Absent": "ያልመጡ",
      "Leave": "ፈቃድ ላይ",
      "Active Zones": "ንቁ የሆኑ ዞኖች",
      "Delayed Zones": "የዘገዩ ዞኖች",
      "Safety Score": "የደህንነት ተገዢነት ደረጃ",
      "Quality Score": "የጥራት ቁጥጥር ደረጃ",
      "Top Performing Workers": "ከፍተኛ ውጤት ያመጡ ሰራተኞች",
      "Top Performing Teams": "ደረጃቸውን የጠበቁ ቡድኖች",
      "Simulate Attendance Tap": "የመግቢያ መለያ መታ መድረክ",
      "Select Worker": "ሰራተኛ ይምረጡ",
      "Select Attendance Method": "የመለያ ዘዴ ይምረጡ",
      "Clock In (IN)": "መግቢያ (IN)",
      "Clock Out (OUT)": "መውጫ (OUT)",
      "Worker Attendance Logs": "የመገኘት መዝገብ ሰሌዳ",
      "Worker Name": "የሰራተኛ ስም",
      "Trade": "የሙያ ዘርፍ",
      "Check In": "የመግቢያ ሰዓት",
      "Check Out": "የመውጫ ሰዓት",
      "Working Hours": "የሰሩበት ሰዓት",
      "Method": "የመለያ መሣሪያ",
      "Status": "ሁኔታ",
      "Project Planner & Scheduler": "የግንባታ ጊዜ እቅድ መርሃ-ግብር",
      "Project Start Date": "ግንባታው የሚጀመርበት ቀን",
      "Number of Floors": "ጠቅላላ የፎቅ ብዛት",
      "Zones per Floor": "በአንድ ፎቅ ውስጥ ያሉ ዞኖች",
      "Target Days per Zone": "የእያንዳንዱ ዞን የቀን ገደብ",
      "Generate Construction Schedule": "የግንባታ የጊዜ ሰሌዳውን በራስ-ሰር አውጣ",
      "Zone Schedule Table": "በራስ-ሰር የተሰራ የግንባታ ሰሌዳ",
      "Record Daily Formwork Progress": "ዕለታዊ የአሉሚኒየም ፎርምወርክ ቁጥጥር",
      "Building & Block": "የህንፃ ብሎክ",
      "Floor & Zone": "ፎቅ",
      "Installed Panels": "የተገጠሙ የአሉሚኒየም ፓነሎች",
      "Removed Panels": "የተነሱ የአሉሚኒየም ፓነሎች",
      "Remaining Panels": "ያልተገጠሙ የቀሩ ፓነሎች",
      "Concrete Ready for Pouring": "ለኮንክሪት ሙሌት ዝግጁ ነው",
      "Inspection Status": "የህንፃ ተቆጣጣሪ ፍቃድ ሁኔታ",
      "Comments": "የእለት ስራዎች ማስታወሻ",
      "Log Daily Progress": "ምዝገባውን መዝግብ",
      "Add Quality Snag": "የጥራት ጉድለቶችን መመዝገቢያ",
      "Defect Type": "የጉድለት አይነት",
      "Active Snags & Repair Status": "ያልተፈቱ የጥራት ጉድለቶች መዝገብ",
    }
  };

  const tabPermissions: Record<UserRole, string[]> = {
    [UserRole.HEAD_OFFICE]: ["dashboard", "attendance", "biometricBoard", "fingerprintBoard", "biometricKiosk", "planning", "progress", "performance", "safetyQuality", "predictions", "admin", "auditLog", "aiInspection"],
    [UserRole.TIME_KEEPER]: ["dashboard", "attendance", "biometricBoard", "fingerprintBoard", "biometricKiosk", "performance", "safetyQuality", "auditLog", "aiInspection"],
    [UserRole.TEAM_LEADER]: ["dashboard", "biometricBoard", "fingerprintBoard", "biometricKiosk", "planning", "progress", "safetyQuality", "auditLog", "aiInspection"],
    [UserRole.GANG_CHIEF]: ["dashboard", "biometricBoard", "fingerprintBoard", "biometricKiosk", "progress", "safetyQuality", "auditLog", "aiInspection"],
    [UserRole.SUPERVISOR]: ["dashboard", "attendance", "biometricBoard", "fingerprintBoard", "biometricKiosk", "progress", "performance", "safetyQuality", "auditLog", "aiInspection"],
    [UserRole.WORKER]: ["dashboard", "attendance", "progress"]
  };

  const t = (key: string): string => {
    const lang = isAmharic ? "am" : "en";
    return translations[lang][key] || key;
  };

  // Enforce strict RBAC on role changes
  React.useEffect(() => {
    const allowed = tabPermissions[currentUserRole];
    if (allowed && !allowed.includes(activeTab)) {
      setActiveTab("dashboard");
    }
  }, [currentUserRole, activeTab]);

  // Audit log generator helper
  const logAction = (action: string, details: string, customizedRole?: UserRole) => {
    const activeRole = customizedRole || currentUserRole;
    const newLog: AuditLog = {
      id: `AUD-${Date.now().toString().slice(-4)}`,
      timestamp: new Date().toISOString().replace("T", " ").slice(0, 19),
      userId: activeRole === UserRole.HEAD_OFFICE ? "HO-01" :
              activeRole === UserRole.TIME_KEEPER ? "TK-01" :
              activeRole === UserRole.TEAM_LEADER ? "TL-01" :
              activeRole === UserRole.GANG_CHIEF ? "GC-01" : "W-101",
      userName: activeRole === UserRole.HEAD_OFFICE ? "Eng. Yoseph (Head Office)" :
                activeRole === UserRole.TIME_KEEPER ? "Abebe Girma (Time Keeper)" :
                activeRole === UserRole.TEAM_LEADER ? "Yohannes Bekele (Team Leader)" :
                activeRole === UserRole.GANG_CHIEF ? "Fikru Tolossa (Gang Chief)" : "Bekele Tesfaye (Worker)",
      role: activeRole,
      action,
      details
    };
    setAuditLogs((prev) => [newLog, ...prev]);
  };

  // State Manipulation Handlers
  const handleAddAttendance = (record: AttendanceRecord) => {
    setAttendance((prev) => {
      const exists = prev.some((r) => r.id === record.id);
      if (exists) {
        return prev.map((r) => (r.id === record.id ? record : r));
      }
      return [record, ...prev];
    });
    logAction("Biometric Attendance Logged", `Clocked ${record.checkOut ? "OUT" : "IN"} worker ${record.workerName} via ${record.method}. Status: ${record.status}`);
  };

  const handleUpdateZone = (updatedZone: ProjectZone) => {
    setZones((prev) => prev.map((z) => (z.id === updatedZone.id ? updatedZone : z)));
    logAction("Zone Plan Updated", `Updated completion stats for Zone ${updatedZone.zone} on floor ${updatedZone.floor}. Overall Completion: ${updatedZone.completionPercentage}%`);
  };

  const handleAddZone = (newZone: ProjectZone) => {
    setZones((prev) => {
      if (prev.some((z) => z.id === newZone.id)) return prev;
      return [...prev, newZone];
    });
    logAction("New Zone Created", `Created structural project zone ${newZone.id} in building ${newZone.building}`);
  };

  const handleAddLog = (newLog: DailyProgressLog) => {
    setProgressLogs((prev) => [newLog, ...prev]);
    logAction("Daily Progress Logged", `Logged formwork metrics for ${newLog.zone}. Installed: ${newLog.installedPanels} panels, Stripped: ${newLog.removedPanels} panels.`);
  };

  const handleAddEvaluation = (newEval: PerformanceEvaluation) => {
    setEvaluations((prev) => [newEval, ...prev]);
    logAction("Worker Performance Evaluated", `Evaluated worker ${newEval.workerName}. Overall Score: ${newEval.totalScore}/100. Rank: ${newEval.level}`);
  };

  const handleAddSafetyLog = (newSafetyLog: SafetyLog) => {
    setSafetyLogs((prev) => [newSafetyLog, ...prev]);
    logAction("Safety Audit Registered", `Logged safety Toolbox topic: "${newSafetyLog.toolboxTopic}". Daily Safety Compliance Index: ${newSafetyLog.safetyScore}%`);
  };

  const handleAddSnag = (newSnag: QualitySnag) => {
    setQualitySnags((prev) => [newSnag, ...prev]);
    logAction("Quality Snag Logged", `Reported structural defect: "${newSnag.description}" under category "${newSnag.defectType}"`);
  };

  const handleResolveSnag = (snagId: string) => {
    setQualitySnags((prev) => 
      prev.map((snag) => snag.id === snagId ? { ...snag, status: "Resolved" } : snag)
    );
    logAction("Quality Snag Resolved", `Marked outstanding defect ID: ${snagId} as Resolved & verified.`);
  };

  // Admin roster operations
  const handleAddWorker = (w: Worker) => {
    setWorkers((prev) => [...prev, w]);
    logAction("Worker Registered", `Added worker ${w.name} (${w.trade}) to department ${w.department}`);
  };

  const handleDeleteWorker = (id: string) => {
    const worker = workers.find(w => w.id === id);
    setWorkers((prev) => prev.filter((w) => w.id !== id));
    logAction("Worker Terminated", `Removed worker ${worker ? worker.name : id} from organization roster`);
  };

  const handleAddTeam = (team: Team) => {
    setTeams((prev) => [...prev, team]);
    logAction("Construction Team Created", `Registered team "${team.name}" in department ${team.department}`);
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col antialiased">
      
      {/* HEADER SECTION (No-print for tidy PDF generation) */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40 no-print shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-red-600 text-white rounded-lg flex items-center justify-center">
              <Building2 size={22} />
            </div>
            <div>
              <span className="text-xs uppercase tracking-widest font-black text-red-600">OVID Group</span>
              <h1 className="text-sm font-extrabold text-slate-900 tracking-tight leading-none">
                Aluminum Formwork Attendance & Productivity System
              </h1>
            </div>
          </div>

          <div className="flex items-center space-x-4">
            {/* Duty user selector */}
            <div className="flex items-center space-x-2 bg-slate-50 p-1.5 rounded-xl border border-slate-200">
              <UserCheck size={14} className="text-red-600 ml-1 shrink-0" />
              <div className="text-left leading-none">
                <span className="text-[9px] text-slate-400 block uppercase font-bold tracking-wider">{isAmharic ? "የተጠቃሚ መለያ" : "Active Session Profile"}</span>
                <select
                  value={currentUserRole}
                  onChange={(e) => {
                    const newRole = e.target.value as UserRole;
                    setCurrentUserRole(newRole);
                    logAction("User Switched Session Role", `Switched acting role session to ${newRole}`, newRole);
                  }}
                  className="bg-transparent border-none text-xs font-bold font-sans text-slate-700 focus:outline-none focus:ring-0 cursor-pointer pr-1"
                >
                  <option value={UserRole.HEAD_OFFICE}>{isAmharic ? "ዋና መስሪያ ቤት (Eng. Yoseph)" : "Head Office - Eng. Yoseph"}</option>
                  <option value={UserRole.TIME_KEEPER}>{isAmharic ? "የመገኘት ተቆጣጣሪ (Abebe Girma)" : "Time Keeper - Abebe Girma"}</option>
                  <option value={UserRole.TEAM_LEADER}>{isAmharic ? "የስራ ቡድን መሪ (Yohannes Bekele)" : "Team Leader - Yohannes Bekele"}</option>
                  <option value={UserRole.GANG_CHIEF}>{isAmharic ? "ጋንግ ቺፍ / ፎርማን (Fikru Tolossa)" : "Gang Chief - Fikru Tolossa"}</option>
                  <option value={UserRole.SUPERVISOR}>{isAmharic ? "ሱፐርቫይዘር (Kassa Hunegn)" : "Supervisor - Kassa Hunegn"}</option>
                  <option value={UserRole.WORKER}>{isAmharic ? "ሳይት ሰራተኛ (Bekele Tesfaye)" : "Worker - Bekele Tesfaye"}</option>
                </select>
              </div>
            </div>

            {/* Language toggle widget */}
            <button
              onClick={() => setIsAmharic(!isAmharic)}
              className="p-2 hover:bg-slate-100 rounded-full text-slate-600 flex items-center space-x-1 transition-colors cursor-pointer"
              title="Toggle Language / ቋንቋ ቀይር"
            >
              <Languages size={18} />
              <span className="text-xs font-bold font-mono">{isAmharic ? "EN" : "አማ"}</span>
            </button>
          </div>
        </div>
      </header>

      {/* CORE NAVIGATION BAR (No-print) */}
      <div className="bg-slate-900 text-slate-300 no-print shadow-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center space-x-1 overflow-x-auto py-1 scrollbar-none whitespace-nowrap text-xs font-semibold">
            
            {/* Dashboard Tab */}
            {tabPermissions[currentUserRole]?.includes("dashboard") && (
              <button
                onClick={() => setActiveTab("dashboard")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "dashboard" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Activity size={15} />
                <span>{t("Dashboard")}</span>
              </button>
            )}

            {/* Attendance Tab */}
            {tabPermissions[currentUserRole]?.includes("attendance") && (
              <button
                onClick={() => setActiveTab("attendance")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "attendance" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Users size={15} />
                <span>{t("Attendance")}</span>
              </button>
            )}

            {/* Biometric Attendance Board Tab */}
            {tabPermissions[currentUserRole]?.includes("biometricBoard") && (
              <button
                onClick={() => setActiveTab("biometricBoard")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "biometricBoard" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Fingerprint size={15} className="text-red-400" />
                <span>{t("Biometric Board")}</span>
              </button>
            )}

            {/* Fingerprint Attendance Board Tab */}
            {tabPermissions[currentUserRole]?.includes("fingerprintBoard") && (
              <button
                onClick={() => setActiveTab("fingerprintBoard")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "fingerprintBoard" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Fingerprint size={15} className="text-red-500 animate-pulse" />
                <span>{t("Fingerprint Board")}</span>
              </button>
            )}

            {/* Biometric Kiosk Tab */}
            {tabPermissions[currentUserRole]?.includes("biometricKiosk") && (
              <button
                onClick={() => setActiveTab("biometricKiosk")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "biometricKiosk" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <ScanLine size={15} className="text-red-500" />
                <span>{t("Biometric Kiosk")}</span>
              </button>
            )}

            {/* Planning & Gantt Scheduler */}
            {tabPermissions[currentUserRole]?.includes("planning") && (
              <button
                onClick={() => setActiveTab("planning")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "planning" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Calendar size={15} />
                <span>{t("Planning")}</span>
              </button>
            )}

            {/* Daily progress logging */}
            {tabPermissions[currentUserRole]?.includes("progress") && (
              <button
                onClick={() => setActiveTab("progress")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "progress" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Layers size={15} />
                <span>{t("Daily Logs")}</span>
              </button>
            )}

            {/* Performance Rankings Tab */}
            {tabPermissions[currentUserRole]?.includes("performance") && (
              <button
                onClick={() => setActiveTab("performance")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "performance" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <UserCheck size={15} />
                <span>{t("Evaluation")}</span>
              </button>
            )}

            {/* Safety and Quality Checks */}
            {tabPermissions[currentUserRole]?.includes("safetyQuality") && (
              <button
                onClick={() => setActiveTab("safetyQuality")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "safetyQuality" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <ShieldAlert size={15} />
                <span>{t("Safety & Quality")}</span>
              </button>
            )}

            {/* AI Site Photo & Concrete Readiness Inspection Tab */}
            {tabPermissions[currentUserRole]?.includes("aiInspection") && (
              <button
                onClick={() => setActiveTab("aiInspection")}
                className={`px-4 py-3 flex items-center space-x-1.5 text-red-400 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "aiInspection" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Camera size={15} />
                <span>{isAmharic ? "አይአይ ፎቶ ቁጥጥር" : "AI Photo Inspection"}</span>
              </button>
            )}

            {/* AI Predictive Analytics */}
            {tabPermissions[currentUserRole]?.includes("predictions") && (
              <button
                onClick={() => setActiveTab("predictions")}
                className={`px-4 py-3 flex items-center space-x-1.5 text-rose-400 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "predictions" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Sparkles size={15} />
                <span>{t("AI Predictions")}</span>
              </button>
            )}

            {/* Admin Setup Tab */}
            {tabPermissions[currentUserRole]?.includes("admin") && (
              <button
                onClick={() => setActiveTab("admin")}
                className={`px-4 py-3 flex items-center space-x-1.5 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "admin" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <Settings size={15} />
                <span>{t("Admin")}</span>
              </button>
            )}

            {/* Audit Log Tab */}
            {tabPermissions[currentUserRole]?.includes("auditLog") && (
              <button
                onClick={() => setActiveTab("auditLog")}
                className={`px-4 py-3 flex items-center space-x-1.5 text-emerald-400 transition-colors cursor-pointer border-b-2 ${
                  activeTab === "auditLog" ? "text-white border-red-500 bg-slate-800" : "border-transparent hover:text-white hover:bg-slate-800"
                }`}
              >
                <ShieldCheck size={15} />
                <span>{isAmharic ? "ኦዲት መዝገብ (Audit Log)" : "Audit Log"}</span>
              </button>
            )}

          </div>
        </div>
      </div>

      {/* PRIMARY VIEWS LAYOUT CONTAINER */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-grow w-full">
        {activeTab === "dashboard" && (
          <Dashboard 
            workers={workers} 
            teams={teams} 
            zones={zones} 
            attendance={attendance} 
            isAmharic={isAmharic}
            t={t}
            activeTab={activeTab}
            setActiveTab={setActiveTab}
            currentUserRole={currentUserRole}
            evaluations={evaluations}
            onAddAttendance={handleAddAttendance}
          />
        )}

        {activeTab === "attendance" && (
          <Attendance 
            workers={workers} 
            attendance={attendance} 
            onAddAttendance={handleAddAttendance} 
            isAmharic={isAmharic}
            t={t}
            currentUserRole={currentUserRole}
            onAddWorker={handleAddWorker}
            onDeleteWorker={handleDeleteWorker}
            evaluations={evaluations}
            onAddEvaluation={handleAddEvaluation}
          />
        )}

        {activeTab === "biometricBoard" && (
          <BiometricAttendanceBoard 
            workers={workers} 
            attendance={attendance} 
            onAddAttendance={handleAddAttendance} 
            isAmharic={isAmharic}
            currentUserRole={currentUserRole}
            onLogAction={(action, details) => logAction(action, details)}
          />
        )}

        {activeTab === "fingerprintBoard" && (
          <FingerprintAttendanceBoard 
            workers={workers} 
            attendance={attendance} 
            onAddAttendance={handleAddAttendance} 
            isAmharic={isAmharic}
            currentUserRole={currentUserRole}
            onLogAction={(action, details) => logAction(action, details)}
          />
        )}

        {activeTab === "biometricKiosk" && (
          <BiometricEnrollmentKiosk 
            workers={workers} 
            attendance={attendance} 
            onAddAttendance={handleAddAttendance} 
            onEnrollWorker={(newWorker) => {
              setWorkers((prev) => [newWorker, ...prev]);
            }}
            isAmharic={isAmharic}
            currentUserRole={currentUserRole}
            onLogAction={(action, details) => logAction(action, details)}
          />
        )}

        {activeTab === "planning" && (
          <PlanningScheduler 
            zones={zones} 
            onUpdateZone={handleUpdateZone} 
            onAddZone={handleAddZone} 
            isAmharic={isAmharic}
            t={t}
            currentUserRole={currentUserRole}
          />
        )}

        {activeTab === "progress" && (
          <DailyProgress 
            logs={progressLogs} 
            onAddLog={handleAddLog} 
            isAmharic={isAmharic}
            t={t}
          />
        )}

        {activeTab === "performance" && (
          <Performance 
            workers={workers} 
            teams={teams} 
            evaluations={evaluations} 
            onAddEvaluation={handleAddEvaluation} 
            isAmharic={isAmharic}
            t={t}
          />
        )}

        {activeTab === "safetyQuality" && (
          <SafetyQuality 
            safetyLogs={safetyLogs} 
            qualitySnags={qualitySnags} 
            qualityLogs={qualityLogs} 
            onAddSafetyLog={handleAddSafetyLog} 
            onAddSnag={handleAddSnag} 
            onResolveSnag={handleResolveSnag} 
            isAmharic={isAmharic}
            t={t}
          />
        )}

        {activeTab === "predictions" && (
          <AIPredictions 
            zones={zones} 
            teams={teams} 
            workers={workers} 
            evaluations={evaluations} 
            progressLogs={progressLogs} 
            safetyLogs={safetyLogs} 
            qualitySnags={qualitySnags} 
            isAmharic={isAmharic}
            t={t}
          />
        )}

        {activeTab === "aiInspection" && (
          <AiPhotoInspection 
            isAmharic={isAmharic}
            currentUserRole={currentUserRole}
            zones={zones}
            onUpdateZone={handleUpdateZone}
            onLogAction={(action, details) => logAction(action, details)}
          />
        )}

        {activeTab === "admin" && tabPermissions[currentUserRole]?.includes("admin") && (
          <AdminPanel 
            workers={workers} 
            teams={teams} 
            currentUserRole={currentUserRole}
            onChangeUserRole={setCurrentUserRole}
            onAddWorker={handleAddWorker}
            onDeleteWorker={handleDeleteWorker}
            onAddTeam={handleAddTeam}
            isAmharic={isAmharic}
            t={t}
          />
        )}

        {activeTab === "auditLog" && tabPermissions[currentUserRole]?.includes("auditLog") && (
          <AuditLogView 
            logs={auditLogs} 
            isAmharic={isAmharic}
            t={t}
          />
        )}
      </main>

      {/* FOOTER SECTION */}
      <footer className="bg-white border-t border-slate-200 py-6 text-center text-xs text-slate-400 no-print">
        <div className="max-w-7xl mx-auto px-4">
          <p>© {new Date().getFullYear()} OVID Real Estate. All rights reserved. Aluminum Formwork Productivity Command Hub.</p>
          <p className="mt-1 font-mono text-[10px]">Secure offline local-sync enabled | Bole Heights Project Site B1</p>
        </div>
      </footer>

    </div>
  );
}
